# Generated by Django 6.0.4 on 2026-05-03 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('experience_years', models.CharField(choices=[('0-1', 'Less than 1 year'), ('1-3', '1–3 years'), ('3-5', '3–5 years'), ('5+', '5+ years')], default='0-1', max_length=10)),
                ('education', models.TextField(blank=True, help_text='Degrees and certifications')),
                ('teaching_style', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated languages', max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('response_time', models.CharField(default='Within 24 hours', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutors', to='tutors.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_profiles',
                'ordering': ['-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='tutors.tutorprofile')),
            ],
            options={
                'db_table': 'tutor_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('tutor', 'day_of_week', 'start_time')},
            },
        ),
    ]
